### ISSUE TITLE
Forge incompatibility

### ISSUE THREAD

**Issue by smokytek** [SuperKali/MCStatusBot#1]
It seems like the StatusBot  can't read properly data from Forge-related server build.
I've tested it with Magma 1.12.2 (Version: v761933c-CUSTOM) and with Forge 1.12.2 (14.23.5.2847).
I have no error on console, just the server tagged as offline and no player count.

**Comment by SuperKali** [comment]
After checking, the possible problem may be:
- No server-side queries enabled.
- The library does not support forge servers.

To bypass this problem, I would have to use an external query, but it's not sure if that's the problem yet.

```
OSError: Server did not respond with any information!
```

**Comment by SuperKali** [comment]
I've created an issue to the creator of the library, I'll wait an answer by them.

https://github.com/py-mine/mcstatus/issues/252

**Comment by SuperKali** [comment]
I've tried to host a forge server, after editing the line of server-query: false to true I checked the response and return the online players without any problem.

```
>>> from mcstatus import MinecraftServer
>>> check = MinecraftServer.lookup("MYIPADDRESS:4004")
>>> print(check.status().players.online)
0 = The online player
```

Have you sure to have checked correctly the query? if there's some plugin that block it? in this case for me the issue is not present.
